version: '3'
services:
  mysql-docker:
    image: 'mysql:5.7'
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_PASSWORD=root123
      - MYSQL_DATABASE=demo
    ports:
      - "3307:3306"
  springboot-mysql-docker-container:
    image: spring-mysql-docker
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-docker:3306/demo?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root123"
    build:
      context: "./"
      dockerfile: "Dockerfile"
    depends_on:
      - mysql-docker
